In [5]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)


1.26.4
2.2.2


In [10]:
# scalars
s = 5;
print(s)

# vectors - creating it ( v - row vector)
v = np.array([1, 2, 3])
print(v)

# matrices - double square bracket
m = np.array([[1,2,3],[4,5,6]])
print(m)

5
[1 2 3]
[[1 2 3]
 [4 5 6]]


In [23]:
# int, n-dimensional array
print(type(s))
print(type(m))
print(type(v))

# another way to create scalars in python
s = np.array(s)
print(type(s))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# checking the shapes of the arrays - that is the dimensions 
print(m.shape)
print(v.shape)
print(s.shape)

(2, 3)
(3,)
()


In [28]:
# we can reshape those arrays using reshape method
print(v.reshape(1,3), v.reshape(3,1))
print(m.reshape(3,2), m.reshape(2,3))

[[1 2 3]] [[1]
 [2]
 [3]]
[[1 2]
 [3 4]
 [5 6]] [[1 2 3]
 [4 5 6]]


In [ ]:
# tensor 
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[7,8,9],[10,11,12]])


print(m1.shape,m2.shape)

# (2,2,3) - 2 matrices, 2*3 
t = np.array([m1,m2])
print(t.shape)

[[ 8 10 12]
 [14 16 18]]
(2, 3) (2, 3)
(2, 2, 3)


In [34]:
t_manual = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]]);
print(t_manual.shape)

(2, 2, 3)


In [36]:
# additions and subtraction of arrays
print(m1 + m2)
print(m1 - m2)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]


In [40]:
# same operations for vectors
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

print(v1-v2)
print(v1+v2)

[-4 -2  0  2  4]
[6 6 6 6 6]


In [42]:
# Transposing matrices
A = np.array([[1,2,3,4],[5,6,7,8]])
print(A)
print(A.T)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [43]:
# dot product 
x = np.array([2,8,-4])
y = np.array([1,-7,3])

print(np.dot(x,y))

-66
